name: EdgeWARN-dev
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - aioboto3
  - boto3
  - cfgrib
  - numpy
  - netcdf4
  - scikit-image
  - scipy
  - shapely
  - rasterio
  - xarray
  - pyproj
  - psutil
  - ijson
  - pip:
    - gputil
    - pytest
    - pytest-mock
    - aiofiles
    - aiohttp
    - requests
    - beautifulsoup4
    - opencv-python-headless
