from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional

from EdgeWARN.alerts.schema import AlertPayload


class AnalysisModule(ABC):
    """
    Abstract base class for all CTAM analysis modules.
    """
    
    @property
    @abstractmethod
    def name(self) -> str:
        """
        The unique name of the module. 
        This will be used as the key in the 'modules' dictionary.
        """
        pass

    @abstractmethod
    def run(self, storm_entry: Dict[str, Any], environment: Optional[Dict[str, Any]] = None, history_cache: Optional[Any] = None) -> None:
        """
        Perform analysis on a single storm entry.

        Parameters:
        - storm_entry: dict containing 'properties' and 'modules'.
                       This dictionary is modified in-place to add results.
        - environment: optional external data (e.g. RAP wind profile, thermodynamics).

        Module writes its results into:
        storm_entry['modules'][self.name]

        Results can include arbitrary parameters or metadata.
        """
        pass

    def alerts(self, storm_entry: Dict[str, Any]) -> Optional[List[AlertPayload]]:
        """
        Return alert payloads generated by this module for a storm entry,
        or None if no alerts are produced.

        Override in modules that emit alerts (e.g. StormCast, Flash Flood).
        The CTAM runner will call this after run() and publish any returned
        payloads via AlertManager.

        Parameters:
        - storm_entry: the same storm entry dict passed to run().

        Returns:
        - A list of AlertPayload objects, or None.
        """
        return None


class GridAnalysisModule(ABC):
    """
    Grid-based module - operates on raw data files (GRIB/NetCDF).
    Does not require storm cells; runs independently on raster data.
    """
    
    @property
    @abstractmethod
    def name(self) -> str:
        """The unique name of the module."""
        pass
    
    @abstractmethod
    def run(self) -> Dict[str, Any]:
        """
        Run grid-based analysis on raw data files.
        
        Returns:
            Dict with:
                - 'features': GeoJSON FeatureCollection of detected regions
                - 'metadata': Processing metadata
                - 'timestamp': Analysis timestamp
        """
        pass
    
    def alerts(self, features: List[Dict[str, Any]]) -> Optional[List[AlertPayload]]:
        """
        Return alert payloads generated by this module,
        or None if no alerts are produced.
        
        Parameters:
        - features: List of GeoJSON features from run() output.
        
        Returns:
        - A list of AlertPayload objects, or None.
        """
        return None
