import math
from datetime import timedelta


NOISE_FLOOR = 0.0035
DETECTION_THRESHOLD = 0.006
MIN_OBJECT_PIXELS = 6
AZSHEAR_GRID_SPACING_DEG = 0.005

SMOOTHING_SIGMA = 1.0
ENABLE_MORPH_CLEANUP = True
MORPH_STRUCTURE_SIZE = 2
ENABLE_TILED_PREPROCESS = True
PREPROCESS_TILE_SIZE = 256
PREPROCESS_HALO_CELLS = 6

REFLECTIVITY_THRESHOLD_DBZ = 38.0
REFLECTIVITY_CORE_DISTANCE_KM = 8.0

VERTICAL_ASSOCIATION_DISTANCE_KM = 7.5
VERTICAL_ASSOCIATION_MIN_OVERLAP_RATIO = 0.05
TRACK_MATCH_DISTANCE_KM = 15.0
TRACK_MEMORY = timedelta(minutes=10)

MAX_COMPONENT_ASPECT_RATIO = 8.0

LOW_LAYER_KEY = "low"
MID_LAYER_KEY = "mid"

STRENGTH_BINS = [
    (0.025, "violent"),
    (0.015, "strong"),
    (0.008, "moderate"),
    (0.006, "weak"),
]

RANK_MIN = DETECTION_THRESHOLD
RANK_MAX = 0.03
MAX_STRENGTH_RANK = 25

CONFIDENCE_WEIGHTS = {
    "azshear": 0.65,
    "depth": 0.2,
    "reflectivity": 0.15,
}

AZSHEAR_UNIT_SCALE_THRESHOLD = 1.0
AZSHEAR_UNIT_DIVISOR = 1000.0


def native_pixel_area_km2(reference_lat: float = 35.0) -> float:
    lat_spacing_km = AZSHEAR_GRID_SPACING_DEG * 111.32
    lon_spacing_km = AZSHEAR_GRID_SPACING_DEG * 111.32 * max(math.cos(math.radians(reference_lat)), 1e-6)
    return lat_spacing_km * lon_spacing_km
