LOW_PEAK_STRONG = 4.0
LOW_PEAK_EXTREME = 8.0
MID_PEAK_STRONG = 2.5
MID_PEAK_EXTREME = 6.0

MAX_VERTICAL_SEPARATION_KM = 10.0
MAX_PEAK_SEPARATION_KM = 12.0
MAX_WIDTH_KM = 18.0
MIN_ELLIPTICITY = 0.25
MIN_ASPECT_RATIO = 1.15

ALIGNMENT_WEIGHT = 0.35
STRENGTH_WEIGHT = 0.4
MORPHOLOGY_WEIGHT = 0.25

MIN_CLASSIFY_CONFIDENCE = 0.45
DEEP_CONFIDENCE = 0.72

PERSISTENCE_HISTORY_LIMIT = 5
PERSISTENCE_STEP = 0.08
PERSISTENCE_CAP = 0.2

PREDICTED_TRACK_PENALTY = 0.15
DECAYING_TRACK_PENALTY = 0.1
